on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: kpspringkubacr.azurecr.io
        username: ${{ secrets.acr_kpspringkubacr_username }}
        password: ${{ secrets.acr_kpspringkubacr_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/Application" -f  "Application/Dockerfile" -t kpspringkubacr.azurecr.io/bugbash1622:${{ github.sha }}
        docker push kpspringkubacr.azurecr.io/bugbash1622:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_bugbash1622_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep bugbash16226aba | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace bugbash16226aba`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: bugbash16226aba
        container-registry-url: kpspringkubacr.azurecr.io
        container-registry-username: ${{ secrets.acr_kpspringkubacr_username }}
        container-registry-password: ${{ secrets.acr_kpspringkubacr_password }}
        secret-name: bugbash1622dockerauth
       
    - uses: azure/k8s-deploy@v1
      with:
        namespace: bugbash16226aba
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
          manifests/ingress.yml
        images: |
          kpspringkubacr.azurecr.io/bugbash1622:${{ github.sha }}
        imagepullsecrets: |
          bugbash1622dockerauth